from datetime import datetime, timezone
from typing import Optional
from sqlalchemy import select, update, insert
import structlog

from core.database import get_engine, leads, dedup_log

log = structlog.get_logger()


def _find_existing(conn, record):
    county = record.get("county", "")

        pid = record.get("parcel_id_normalized", "")
            if pid and county:
                    row = conn.execute(
                                select(leads.c.id).where(
                                                leads.c.parcel_id_normalized == pid,
                                                                leads.c.county == county,
                                                                            )
                                                                                    ).fetchone()
                                                                                            if row:
                                                                                                        return row[0], "parcel_id"

                                                                                                            addr = record.get("property_address_normalized", "")
                                                                                                                if addr and county:
                                                                                                                        row = conn.execute(
                                                                                                                                    select(leads.c.id).where(
                                                                                                                                                    leads.c.property_address_normalized == addr,
                                                                                                                                                                    leads.c.county == county,
                                                                                                                                                                                )
                                                                                                                                                                                        ).fetchone()
                                                                                                                                                                                                if row:
                                                                                                                                                                                                            return row[0], "address"

                                                                                                                                                                                                                owner = record.get("owner_name_normalized", "")
                                                                                                                                                                                                                    mail  = record.get("mailing_address_normalized", "")
                                                                                                                                                                                                                        if owner and mail:
                                                                                                                                                                                                                                row = conn.execute(
                                                                                                                                                                                                                                            select(leads.c.id).where(
                                                                                                                                                                                                                                                            leads.c.owner_name_normalized == owner,
                                                                                                                                                                                                                                                                            leads.c.mailing_address_normalized == mail,
                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                ).fetchone()
                                                                                                                                                                                                                                                                                                        if row:
                                                                                                                                                                                                                                                                                                                    return row[0], "owner_mail"

                                                                                                                                                                                                                                                                                                                        docket = record.get("docket_number", "")
                                                                                                                                                                                                                                                                                                                            if docket:
                                                                                                                                                                                                                                                                                                                                        row = conn.execute(
                                                                                                                                                                                                                                                                                                                                                    select(leads.c.id).where(leads.c.docket_number == docket)
                                                                                                                                                                                                                                                                                                                                                            ).fetchone()
                                                                                                                                                                                                                                                                                                                                                                    if row:
                                                                                                                                                                                                                                                                                                                                                                                return row[0], "docket"

                                                                                                                                                                                                                                                                                                                                                                                    return None, None


                                                                                                                                                                                                                                                                                                                                                                                    def upsert_lead(record, engine=None):
                                                                                                                                                                                                                                                                                                                                                                                            eng = engine or get_engine()
                                                                                                                                                                                                                                                                                                                                                                                                now = datetime.now(timezone.utc)

                                                                                                                                                                                                                                                                                                                                                                                                    with eng.begin() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                            existing_id, method = _find_existing(conn, record)

                                                                                                                                                                                                                                                                                                                                                                                                                    if existing_id:
                                                                                                                                                                                                                                                                                                                                                                                                                                conn.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                update(leads).where(leads.c.id == existing_id).values(last_seen_at=now)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.execute(insert(dedup_log).values(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            canonical_id=existing_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dedup_method=method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resolved_at=now,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return existing_id, False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result = conn.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                insert(leads).values(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        **{k: v for k, v in record.items() if k in leads.c.keys()},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            first_seen_at=now,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                last_seen_at=now,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status="new",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new_id = result.inserted_primary_key[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    log.info("dedupe.new_lead", lead_id=new_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new_id, True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))